name: MAJ du reporting
on:
 schedule: 
   - cron: '40 05 * * *'
    
jobs:
  autoscrape:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: quarto-dev/quarto-actions/setup@v2
     
      - name: Install packages
        run: Rscript libs.R
    
      - name: Script
        run: Rscript main.R
        
      - name: Commit files
        run: |
          git config --local user.name github-actions
          git config --local user.email "actions@github.com"
          git add index.html
          git commit -am "commit on $(date)"
          git push origin master
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
